apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gcr.io/lexluthor/app:v1
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
  selector:
    app: myapp
